# Generated by Django 5.1.1 on 2024-11-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0002_remove_farm_description_farm_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='owner',
        ),
    ]
