# Generated by Django 5.1.1 on 2024-11-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0006_farm_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='location',
            new_name='rates',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='image',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='type',
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_type',
            field=models.CharField(choices=[('iron', 'Iron Farm'), ('gold', 'Gold Farm'), ('wood', 'Wood Farm'), ('food', 'Food Farm'), ('mob', 'Mob Farm')], default='iron', max_length=50),
        ),
        migrations.AddField(
            model_name='farm',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1),
        ),
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='farm',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='farm',
            name='tutorial_link',
            field=models.URLField(),
        ),
    ]
